/**
 * Domain literals shared by every workspace (api, worker, web).
 * Nothing in this project may re-type one of these strings inline —
 * import the constant instead (enforced by ESLint no-restricted-syntax, see Coding Standards §4).
 */

/** Certificate lifecycle states (SRS §4.3, LLD §4.4). */
export const CERT_STATE = Object.freeze({
  PENDING_STORAGE: 'PENDING_STORAGE',
  PENDING_ANCHOR: 'PENDING_ANCHOR',
  ANCHORING: 'ANCHORING',
  ACTIVE: 'ACTIVE',
  REVOKING: 'REVOKING',
  REVOKED: 'REVOKED',
  FAILED: 'FAILED',
});

/**
 * Legal transitions out of each state. `lifecycle.service.js` is the only module
 * permitted to write `certificate.status`, and only along one of these edges (rule D5).
 */
export const CERT_STATE_TRANSITIONS = Object.freeze({
  [CERT_STATE.PENDING_STORAGE]: [CERT_STATE.PENDING_ANCHOR, CERT_STATE.FAILED],
  [CERT_STATE.PENDING_ANCHOR]: [CERT_STATE.ANCHORING, CERT_STATE.FAILED],
  [CERT_STATE.ANCHORING]: [CERT_STATE.ACTIVE, CERT_STATE.FAILED],
  [CERT_STATE.ACTIVE]: [CERT_STATE.REVOKING],
  [CERT_STATE.REVOKING]: [CERT_STATE.REVOKED, CERT_STATE.ACTIVE],
  [CERT_STATE.REVOKED]: [],
  [CERT_STATE.FAILED]: [],
});

/** States that are not yet safe to disclose to a public verifier (BR-06/BR-07). */
export const CERT_STATE_NOT_PUBLIC = Object.freeze([
  CERT_STATE.PENDING_STORAGE,
  CERT_STATE.PENDING_ANCHOR,
  CERT_STATE.ANCHORING,
  CERT_STATE.FAILED,
]);

/** The four public verification outcomes (FR-VER-003). Exactly one is ever returned. */
export const VERIFY_OUTCOME = Object.freeze({
  VERIFIED: 'VERIFIED',
  REVOKED: 'REVOKED',
  TAMPERED: 'TAMPERED',
  NOT_FOUND: 'NOT_FOUND',
});

export const VERIFICATION_METHOD = Object.freeze({
  QR_CODE: 'QR_CODE',
  CERT_ID: 'CERT_ID',
  HASH: 'HASH',
});

/** The two authenticated roles. Anonymous verifiers hold no role at all (SRS §2.3). */
export const ROLE = Object.freeze({
  INSTITUTION: 'institution',
  STUDENT: 'student',
});

export const CERTIFICATE_TYPE = Object.freeze({
  DEGREE: 'DEGREE',
  DIPLOMA: 'DIPLOMA',
  COURSE_COMPLETION: 'COURSE_COMPLETION',
});

export const TRANSACTION_TYPE = Object.freeze({
  ISSUE: 'ISSUE',
  REVOKE: 'REVOKE',
});

export const TRANSACTION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  FAILED: 'FAILED',
});

export const INSTITUTION_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
});

export const ACCOUNT_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  DISABLED: 'DISABLED',
});

/** Stable, published API error codes (LLD §6, error catalogue). */
export const ERROR_CODE = Object.freeze({
  E_VALIDATION: 'E_VALIDATION',
  E_INVALID_CERT_NUMBER: 'E_INVALID_CERT_NUMBER',
  E_HOLDER_NOT_FOUND: 'E_HOLDER_NOT_FOUND',
  E_REASON_REQUIRED: 'E_REASON_REQUIRED',
  E_REASON_TOO_LONG: 'E_REASON_TOO_LONG',
  E_UNAUTHENTICATED: 'E_UNAUTHENTICATED',
  E_TOKEN_EXPIRED: 'E_TOKEN_EXPIRED',
  E_FORBIDDEN: 'E_FORBIDDEN',
  E_NOT_FOUND: 'E_NOT_FOUND',
  E_DUPLICATE_CERTIFICATE: 'E_DUPLICATE_CERTIFICATE',
  E_CERT_NOT_ACTIVE: 'E_CERT_NOT_ACTIVE',
  E_ALREADY_REVOKED: 'E_ALREADY_REVOKED',
  E_NOT_ANCHORED: 'E_NOT_ANCHORED',
  E_ILLEGAL_TRANSITION: 'E_ILLEGAL_TRANSITION',
  E_CERT_NUMBER_COLLISION: 'E_CERT_NUMBER_COLLISION',
  E_RATE_LIMITED: 'E_RATE_LIMITED',
  E_PDF_COMPILE_FAILED: 'E_PDF_COMPILE_FAILED',
  E_DOCUMENT_TOO_LARGE: 'E_DOCUMENT_TOO_LARGE',
  E_ISSUER_NOT_REGISTERED: 'E_ISSUER_NOT_REGISTERED',
  E_CHAIN_UNKNOWN: 'E_CHAIN_UNKNOWN',
  E_INTERNAL: 'E_INTERNAL',
  E_PINATA_FAILED: 'E_PINATA_FAILED',
  E_IPFS_UNAVAILABLE: 'E_IPFS_UNAVAILABLE',
  E_RPC_UNAVAILABLE: 'E_RPC_UNAVAILABLE',
  E_CUSTODIAN_UNDERFUNDED: 'E_CUSTODIAN_UNDERFUNDED',
  E_DB_UNAVAILABLE: 'E_DB_UNAVAILABLE',
  E_IDENTITY_UNAVAILABLE: 'E_IDENTITY_UNAVAILABLE',
  E_WEBHOOK_SIGNATURE: 'E_WEBHOOK_SIGNATURE',
  E_WEBHOOK_REPLAY: 'E_WEBHOOK_REPLAY',
});

/** HTTP status mapped per error code (LLD §6). Anything not listed defaults to 500. */
export const ERROR_STATUS = Object.freeze({
  [ERROR_CODE.E_VALIDATION]: 400,
  [ERROR_CODE.E_INVALID_CERT_NUMBER]: 400,
  [ERROR_CODE.E_HOLDER_NOT_FOUND]: 400,
  [ERROR_CODE.E_REASON_REQUIRED]: 400,
  [ERROR_CODE.E_REASON_TOO_LONG]: 400,
  [ERROR_CODE.E_UNAUTHENTICATED]: 401,
  [ERROR_CODE.E_TOKEN_EXPIRED]: 401,
  [ERROR_CODE.E_WEBHOOK_SIGNATURE]: 401,
  [ERROR_CODE.E_WEBHOOK_REPLAY]: 401,
  [ERROR_CODE.E_FORBIDDEN]: 403,
  [ERROR_CODE.E_NOT_FOUND]: 404,
  [ERROR_CODE.E_DUPLICATE_CERTIFICATE]: 409,
  [ERROR_CODE.E_CERT_NOT_ACTIVE]: 409,
  [ERROR_CODE.E_ALREADY_REVOKED]: 409,
  [ERROR_CODE.E_NOT_ANCHORED]: 409,
  [ERROR_CODE.E_ILLEGAL_TRANSITION]: 409,
  [ERROR_CODE.E_CERT_NUMBER_COLLISION]: 409,
  [ERROR_CODE.E_RATE_LIMITED]: 429,
  [ERROR_CODE.E_PDF_COMPILE_FAILED]: 500,
  [ERROR_CODE.E_DOCUMENT_TOO_LARGE]: 500,
  [ERROR_CODE.E_ISSUER_NOT_REGISTERED]: 500,
  [ERROR_CODE.E_CHAIN_UNKNOWN]: 500,
  [ERROR_CODE.E_INTERNAL]: 500,
  [ERROR_CODE.E_PINATA_FAILED]: 503,
  [ERROR_CODE.E_IPFS_UNAVAILABLE]: 503,
  [ERROR_CODE.E_RPC_UNAVAILABLE]: 503,
  [ERROR_CODE.E_CUSTODIAN_UNDERFUNDED]: 503,
  [ERROR_CODE.E_DB_UNAVAILABLE]: 503,
  [ERROR_CODE.E_IDENTITY_UNAVAILABLE]: 503,
});

/** Crockford Base32 alphabet used for certificate-number random components (excludes I,L,O,U). */
export const CROCKFORD_BASE32_ALPHABET = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
